services:
  server:
    # Appache
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - referee
      - ai
    networks:
      - chessnet

  referee:
    build: ./referee
    ports:
      - "5001:5001"
    networks:
      - chessnet
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5001 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  ai:
    build: ./ai
    # environment:
    #   POSTGRES_USER:     /run/secrets/POSTGRES_USER
    #   POSTGRES_PASSWORD: /run/secrets/POSTGRES_PASSWORD
    #   POSTGRES_DB:       /run/secrets/POSTGRES_DB
    ports:
      - "5002:5002"
    depends_on:
      - db
    networks:
      - chessnet
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5002 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

  db:
    build: ./db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - chessnet
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

networks:
  chessnet:
    driver: bridge
volumes:
  db_data:

secrets:
  POSTGRES_USER:
    file: ./secrets/POSTGRES_USER
  POSTGRES_PASSWORD:
    file: ./secrets/POSTGRES_PASSWORD
  POSTGRES_DB:
    file: ./secrets/POSTGRES_DB
