services:
  server:
    image: httpd:latest
    ports:
      - "80:80"
    depends_on:
      - referee
      - ai
    networks:
      - chessnet
    volumes:
      - ./server/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./server/web:/usr/local/apache2/htdocs:ro

  referee:
    build: ./referee
    ports:
      - "5001:5001"
    networks:
      - chessnet

  ai:
    build: ./ai
    ports:
      - "5002:5002"
    depends_on:
      - db
    networks:
      - chessnet
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      # Mount initialization script and data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./db/data.csv:/docker-entrypoint-initdb.d/data.csv:ro
      # Persistent volume for database files
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER_FILE: /run/secrets/POSTGRES_USER
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
      POSTGRES_DB_FILE: /run/secrets/POSTGRES_DB
    networks:
      - chessnet
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

networks:
  chessnet:
    driver: bridge
volumes:
  db_data:

secrets:
  POSTGRES_USER:
    file: ./secrets/POSTGRES_USER
  POSTGRES_PASSWORD:
    file: ./secrets/POSTGRES_PASSWORD
  POSTGRES_DB:
    file: ./secrets/POSTGRES_DB
