services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - referee  # The server only communicates with the referee
      - ai
    networks:
      - chessnet

  referee:
    build: ./referee
    ports:
      - "5001:5001"
    networks:
      - chessnet
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5001 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  ai:
    build: ./ai
    ports:
      - "5002:5002"
    depends_on:
      - db  # The AI depends on the db being ready
    networks:
      - chessnet
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5002 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  db:
    build: ./db
    environment:
      POSTGRES_USER: chess_user
      POSTGRES_PASSWORD: chess_pass
      POSTGRES_DB: chess_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - chessnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chess_user"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  chessnet:
    driver: bridge
volumes:
  db_data:
