#!/bin/sh

set -eu

C="\e[92m"
R="\e[0m"

quiet=true
image_name="postgres-chess-db"
container_name="db-1"
db_port=5432

[ -f ../PASSWORD ] && cat ../PASSWORD | sudo -S -v

# Check if the image exists; if not, build it
if ! sudo docker images | grep -q "$image_name"; then
    printf "${C}%s${R}\n" "Building image $image_name"
    sudo docker build -t $image_name .
else
    printf "${C}%s${R}\n" "Image $image_name exists. Skipping build."
fi

# Check if the container is running; if so, stop and remove it
printf "${C}%s${R}\n" "Dealing with active $container_name container"
if sudo docker ps -a | grep -q "$container_name"; then
    sudo docker stop "$container_name" && sudo docker rm "$container_name"
    printf "${C}%s${R}\n" "Stopped and removed existing $container_name container"
fi

# Run the container
printf "${C}%s${R}\n" "Running $container_name container"
sudo docker run -d --name $container_name -p $db_port:$db_port $image_name

# Wait for the database to be accessible
printf "${C}%s${R}\n" "Checking database..."
sleep 1
while ! sudo docker exec -it "$container_name" psql -U root -d chess_db -c "\dt;" 2> /dev/null; do
    printf "${C}%s${R}\n" "Database is not ready yet, waiting..."
    sleep 1
done

# quick check
if ! $quiet; then
    sudo docker exec -it db-1 psql -U numen -d chess_db -c "\dt;"
    #       List of relations
    # Schema | Name  | Type  | Owner 
    #--------+-------+-------+-------
    # public | games | table | numen
    sudo docker exec -it db-1 psql -U numen -d chess_db -c "SELECT count(*) FROM games;"
    # 20058
    sudo docker exec -it db-1 psql -U numen -d chess_db -c "SELECT count(*) FROM games WHERE result = 'w';"
    # 10001
    sudo docker exec -it db-1 psql -U numen -d chess_db -c "SELECT count(*) FROM games WHERE result = 'b';"
    #  9107
    sudo docker exec -it db-1 psql -U numen -d chess_db -c "SELECT count(*) FROM games WHERE result = 'd';"
    #   950
fi


printf "${C}%s${R}\n" "Going deep ( -[]~[])"
sudo docker exec -it db-1 psql -U numen -d chess_db

printf "${C}%s${R}\n" "Welcome back master \(OoO)/"
