#!/bin/sh

IN=games.csv
OUT=my_games.csv


# from:
#   id,rated,created_at,last_move_at,turns,victory_status,winner,increment_code,white_id,white_rating,black_id,black_rating,moves,opening_eco,opening_name,opening_ply
# to:
#   white_elo,black_elo,white_result,moves
echo "result,white_elo,black_elo,moves" > $OUT
tail -n +2 $IN | cut -d , -f7,10,12,13 | sed "s/^white/w/;s/^black/b/;s/^draw/d/" >> $OUT
