# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: chess-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      automountServiceAccountToken: false  # Disable automatic service account token mount
      containers:
        - name: db
          image: postgres:13
          securityContext:
            readOnlyRootFilesystem: false  # Ensure the filesystem is writable
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
            - name: postgres-secrets
              mountPath: /run/secrets
              readOnly: true
            - name: db-persistent-storage
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_USER_FILE
              value: "/run/secrets/POSTGRES_USER"
            - name: POSTGRES_PASSWORD_FILE
              value: "/run/secrets/POSTGRES_PASSWORD"
            - name: POSTGRES_DB_FILE
              value: "/run/secrets/POSTGRES_DB"
      volumes:
        - name: init-scripts
          hostPath:
            path: /mnt/data/db
            type: Directory
        - name: postgres-secrets
          secret:
            secretName: postgres-secrets
        - name: db-persistent-storage
          persistentVolumeClaim:
            claimName: db-pvc
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: chess-app
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
