#!/bin/sh

# set -eu

echo "[minikube stop]"
minikube stop
echo "[minikube delete]"
minikube delete
echo "[minikube start]"
minikube start \
    --mount-string="$(dirname $(pwd))/:/mnt/data" --mount \
    --driver=docker

# kubectl delete pvc db-pvc -n chess-app

# kubectl get services -n chess-app
# kubectl get pods -n chess-app
